# Generated by Django 2.1.5 on 2021-04-17 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210417_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
