# Generated by Django 2.1.5 on 2021-04-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210417_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='min_price',
        ),
    ]
