# Generated by Django 2.1.5 on 2021-04-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='price',
        ),
    ]
