# Generated by Django 2.1.5 on 2021-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listing',
            name='min_price',
            field=models.FloatField(default=1.0),
        ),
    ]
