# Generated by Django 2.1.5 on 2021-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210417_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
