# Generated by Django 2.1.5 on 2021-04-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='img',
        ),
        migrations.AddField(
            model_name='listing',
            name='imgfile',
            field=models.ImageField(default='default.jpg', upload_to='images/%Y/%m/%d'),
        ),
    ]
