# Generated by Django 2.1.5 on 2021-04-26 10:33

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210423_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imgfile',
            field=models.ImageField(default='default.jpg', upload_to=auctions.models.user_directory_path),
        ),
    ]
