# Generated by Django 2.1.5 on 2021-04-26 16:07

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210426_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imgfile',
            field=models.ImageField(blank=True, upload_to=auctions.models.user_directory_path),
        ),
    ]
