# Generated by Django 2.1.5 on 2021-05-07 13:04

import auctions.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210507_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='time_sent',
        ),
        migrations.AddField(
            model_name='listing',
            name='time_ending',
            field=models.DateTimeField(default=auctions.models.ending_date),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
