# Generated by Django 2.1.5 on 2021-05-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210507_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='pub_date',
            new_name='time_starting',
        ),
    ]
