# Generated by Django 2.1.5 on 2021-05-21 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
